default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: TeamLunchDemo_development


test:
  <<: *default
  database: TeamLunchDemo_test


# production:
#   <<: *default
#   database: TeamLunchDemo_production
#   username: TeamLunchDemo
#   password: <%= ENV['TEAMLUNCHDEMO_DATABASE_PASSWORD'] %>
